apiVersion: v1
kind: Service
metadata:
  name: sejuta-cita-mysql
  labels:
    app: sejuta-cita-api
spec:
  ports:
    - port: 3306
  selector:
    app: sejuta-cita-api
  clusterIP: None
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pv-claim
  labels:
    app: sejuta-cita-api
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
  labels:
    app: sejuta-cita-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sejuta-cita-api
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: sejuta-cita-api
    spec:
      containers:
      - image: mysql:5.5.51
        name: mysql
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: root
        - name: MYSQL_DATABASE
          value: sc-test
        - name: MYSQL_USER
          value: sejutacita
        - name: MYSQL_PASSWORD
          value: SejutaCita
        ports:
        - containerPort: 3306
          name: mysql
        volumeMounts:
        - name: mysql-persistent-storage
          mountPath: /var/lib/mysql
      volumes:
      - name: mysql-persistent-storage
        persistentVolumeClaim:
          claimName: mysql-pv-claim
---

apiVersion: v1
kind: Service
metadata:
  name: sejuta-cita-service
spec:
  type: NodePort
  selector:
    app: sejuta-cita-api
  ports:
    - port: 3000
      targetPort: 3000
      nodePort: 30000

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sejuta-cita-deployment
spec:
  replicas: 1
  selector:
    matchLabels: 
      app: sejuta-cita-api
  template:
    metadata:
      labels:
        app: sejuta-cita-api
    spec:
      containers:
        - name: sejuta-cita-container
          image: ranggabp12/sejuta-cita-api:1.0.0
          ports:
            - containerPort: 3000
          env:
            - name: DB_HOST
              value: sejuta-cita-mysql.default.svc.cluster.local
            - name: DB_PORT
              value: "3306"
            - name: DB_DATABASE
              value: sc-test
            - name: DB_USERNAME
              value: sejutacita
            - name: DB_PASSWORD
              value: SejutaCita
            - name: JWT_SECRET
              value: MYSECRET
            - name: JWT_EXPIRES
              value: 300s

